<?php

namespace ContainerPMw78hQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_32Ynkr6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.32Ynkr6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.32Ynkr6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'prestation' => ['privates', 'App\\Repository\\PrestationRepository', 'getPrestationRepositoryService', true],
        ], [
            'prestation' => 'App\\Repository\\PrestationRepository',
        ]);
    }
}
