<?php

namespace ContainerSYUynYa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CaKoe8HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.caKoe8H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.caKoe8H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'artiste' => ['privates', 'App\\Repository\\ArtisteRepository', 'getArtisteRepositoryService', true],
        ], [
            'artiste' => 'App\\Repository\\ArtisteRepository',
        ]);
    }
}
