<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Artiste extends \App\Entity\Artiste implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'Pseudo', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'localisation', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'imgArtiste', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'estGroupe', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'prestation', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'dr_type_artiste'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'Pseudo', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'localisation', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'imgArtiste', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'estGroupe', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'prestation', '' . "\0" . 'App\\Entity\\Artiste' . "\0" . 'dr_type_artiste'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Artiste $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPseudo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPseudo', []);

        return parent::getPseudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPseudo(?string $Pseudo): \App\Entity\Artiste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPseudo', [$Pseudo]);

        return parent::setPseudo($Pseudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalisation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalisation', []);

        return parent::getLocalisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalisation(?string $localisation): \App\Entity\Artiste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalisation', [$localisation]);

        return parent::setLocalisation($localisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgArtiste(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgArtiste', []);

        return parent::getImgArtiste();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgArtiste(?string $imgArtiste): \App\Entity\Artiste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgArtiste', [$imgArtiste]);

        return parent::setImgArtiste($imgArtiste);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Artiste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstGroupe(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstGroupe', []);

        return parent::getEstGroupe();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstGroupe(bool $estGroupe): \App\Entity\Artiste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstGroupe', [$estGroupe]);

        return parent::setEstGroupe($estGroupe);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrestation(): ?\App\Entity\Prestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrestation', []);

        return parent::getPrestation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrestation(\App\Entity\Prestation $prestation): \App\Entity\Artiste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrestation', [$prestation]);

        return parent::setPrestation($prestation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDrTypeArtiste(): ?\App\Entity\DrTypeArtiste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDrTypeArtiste', []);

        return parent::getDrTypeArtiste();
    }

    /**
     * {@inheritDoc}
     */
    public function setDrTypeArtiste(?\App\Entity\DrTypeArtiste $dr_type_artiste): \App\Entity\Artiste
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDrTypeArtiste', [$dr_type_artiste]);

        return parent::setDrTypeArtiste($dr_type_artiste);
    }

}
