<?php

namespace ContainerAvx4qBY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_91mXXE0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.91mXXE0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.91mXXE0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['privates', '.errored..service_locator.91mXXE0.Doctrine\\Bundle\\DoctrineBundle\\Registry', NULL, 'Cannot autowire service ".service_locator.91mXXE0": it references class "Doctrine\\Bundle\\DoctrineBundle\\Registry" but no such service exists. Try changing the type-hint to "Doctrine\\Persistence\\ManagerRegistry" instead.'],
        ], [
            'doctrine' => 'Doctrine\\Bundle\\DoctrineBundle\\Registry',
        ]);
    }
}
