<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZQvwONx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZQvwONx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZQvwONx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZQvwONx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZQvwONx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZQvwONx',
    'container.build_id' => 'f23748e8',
    'container.build_time' => 1641828458,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZQvwONx');
