<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRdUCKxf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRdUCKxf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRdUCKxf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRdUCKxf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRdUCKxf\App_KernelDevDebugContainer([
    'container.build_hash' => 'RdUCKxf',
    'container.build_id' => '765900ff',
    'container.build_time' => 1641803814,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRdUCKxf');
